### ISSUE TITLE
faker data can get stranded if seeder or test exits instead of returning and transaction doesnt roll back

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/TripalTestSuite#71]
idea:  what if we made everything that faker creates use a special prop for easy deletion
ie the fake base class inserts into [tablename]prop of term local:faker_inserted_data value = true

possible downside: things inserted with a seeder might want to be persistent.

**Comment by bradfordcondon** [comment]
by faker i mean factory

**Comment by almasaeed2010** [comment]
Yeah it's not possible that way to determine what should be persistent.

I think a better solution is to ensure that the transaction is rolled back even on normal shutdown (ie exit()).

**Comment by bradfordcondon** [comment]
yep that would be a better solution.  let's do it that way please.

**Comment by almasaeed2010** [comment]
Ok we now guarantee that graceful or fatal shutdown will rollback all registered transactions.

Of course, this still requires that you `use DBTransaction` trait and that you do not override `setUp()` without calling `parent::setUp()`. Otherwise, all data should be rolled back as excepted.

This will be available in v1.3.0
